/**:
  ros__parameters:
    output_frame: base_link
    # has_static_tf_only: true
    input_topics: [
                    "/sensing/radar/front/pointcloud/amplitude_pointcloud", #pipeline -> pointcloud 
                    "/sensing/radar/left/pointcloud/amplitude_pointcloud",  #pipeline -> pointcloud
                    "/sensing/radar/rear/pointcloud/amplitude_pointcloud",  #pipeline -> pointcloud
                    "/sensing/radar/right/pointcloud/amplitude_pointcloud", #pipeline -> pointcloud
                    # /sensing/radar/front/tracks/pointcloud_from_tracks, #pipeline -> tracks
                    # /sensing/radar/right/tracks/pointcloud_from_tracks, #pipeline -> tracks
                    # /sensing/radar/left/tracks/pointcloud_from_tracks,  #pipeline -> tracks
                    # /sensing/radar/rear/tracks/pointcloud_from_tracks   #pipeline -> tracks
                ]
    # max_queue_size: 5
    # timeout_sec: 0.11
    debug_mode: false
    rosbag_length: 10.0
    maximum_queue_size: 5
    timeout_sec: 0.2
    is_motion_compensated: false
    publish_synchronized_pointcloud: true
    keep_input_frame_in_synchronized_pointcloud: true
    publish_previous_but_late_pointcloud: false
    synchronized_pointcloud_postfix: pointcloud
    input_twist_topic_type: twist
    input_offset: [0.0 ,0.0 ,0.0]
    matching_strategy:
      type: naive
    # input_topics: [
    #                 "/sensing/lidar/right/pointcloud_before_sync",
    #                 "/sensing/lidar/top/pointcloud_before_sync",
    #                 "/sensing/lidar/left/pointcloud_before_sync",
    #             ]
    # output_frame: base_link
    # matching_strategy:
    #   type: advanced
    #   lidar_timestamp_offsets: [0.0, 0.015, 0.016]
    #   lidar_timestamp_noise_window: [0.01, 0.01, 0.01]
